CREATE OR REPLACE FUNCTION seguimiento_incidente()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
DECLARE
BEGIN
  INSERT INTO SEGUIMIENTO_INCIDENTE VALUES(NEW.incidente_id, NEW.incidente_id, 'NO RESUELTO');
  RETURN NEW;
END;
$$

CREATE OR REPLACE TRIGGER seguimiento_incidente
  AFTER INSERT
  ON INCIDENTE
  FOR EACH ROW
  EXECUTE PROCEDURE seguimiento_incidente();